name: test

on:
  push: [ master, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: ./gradlew build

      - run: ./gradlew check

      - run: ./gradlew test